services:
  cloudreve:
    container_name: cloudreve
    image: cloudreve/cloudreve:latest
    networks:
      - caddy
      - internal
    restart: unless-stopped
    volumes:
      - temp_data:/data
      - ./cloudreve/uploads:/cloudreve/uploads
      - ./cloudreve/conf.ini:/cloudreve/conf.ini
      - ./cloudreve/cloudreve.db:/cloudreve/cloudreve.db
      - ./cloudreve/avatar:/cloudreve/avatar
    depends_on:
      - aria2
    labels:
      caddy: ${DOMAIN}
      caddy.reverse_proxy: "{{upstreams 5212}}"
      caddy.tls: "/etc/ssl/certs/caddy/certificate.pem /etc/ssl/private/caddy/key.pem"

  aria2:
    container_name: aria2
    image: p3terx/aria2-pro
    networks:
      - internal
    restart: unless-stopped
    environment:
      - RPC_SECRET=${RPC_SECRET}
      - RPC_PORT=6800
    volumes:
      - ./aria2/config:/config
      - ./aria2/downloads:/downloads
      - temp_data:/data

volumes:
  temp_data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/data
      o: bind

networks:
  caddy:
    external: true
  internal:
    external: false
    driver: bridge